#!/usr/bin/env php-cgi -q
<?php
namespace PUnicorn;

// USES      ////////////////////////////////////////////////////////


// CONSTANTS ////////////////////////////////////////////////////////

// REQUIRES  ////////////////////////////////////////////////////////

require_once 'vendor/autoload.php';

// MAIN      ////////////////////////////////////////////////////////

error_reporting(true);
Logger::log( 'initializing ubik' );

set_error_handler(function($number, $string) { 
  Logger::log( "$number : $string" );
});

// evaluate command line arguments
// @TODO this doesnt work in php-cgi environment
//$arguments = Util\Flag::parse(function($f) {
//	$f->string('config', 'Path to configuration file');
//});

// evaluate configuration 
try { 
	Configuration::evaluate( './config/application.php' );

} catch(\Exception $e) {
	// @TODO add meaningful message
	throws( $e );
} 

// now that we have configuration set, we need to create
// instance of server, which will be response for kicking
// off master/worker processes
@Server::start();